<a href="https://colab.research.google.com/github/devarsh3453/NEW/blob/main/Feature_Construction_Splitting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd
import seaborn as sns

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score

In [3]:
df=pd.read_csv("/content/train.csv")[['Age','Pclass','SibSp','Parch','Survived']]

In [4]:
df.head()

    Age  Pclass  SibSp  Parch  Survived
0  22.0       3      1      0         0
1  38.0       1      1      0         1
2  26.0       3      0      0         1
3  35.0       1      1      0         1
4  35.0       3      0      0         0

In [5]:
df.dropna(inplace=True)

In [6]:
X=df.iloc[:,0:4]
y=df.iloc[:,-1]

In [7]:
cv_scores=cross_val_score(LogisticRegression(),X,y,scoring="accuracy",cv=20)

In [8]:
np.mean(cv_scores)

np.float64(0.6933333333333332)

#Feature Construction

In [9]:
X['Family']=X['SibSp']+X['Parch']+1

In [10]:
X.sample(12)

      Age  Pclass  SibSp  Parch  Family
494  21.0       3      0      0       1
862  48.0       1      0      0       1
369  24.0       1      0      0       1
232  59.0       2      0      0       1
535   7.0       2      0      2       3
220  16.0       3      0      0       1
279  35.0       3      1      1       3
123  32.5       2      0      0       1
725  20.0       3      0      0       1
103  33.0       3      0      0       1
817  31.0       2      1      1       3
10    4.0       3      1      1       3

In [11]:
def fun1(num):
  if num==1:
    return 0
  elif num<=4:
    return 1
  else:
    return 2

In [12]:
fun1(1)

0

In [13]:
X['Family_Type']=X['Family'].apply(fun1)

In [14]:
X.sample(12)

      Age  Pclass  SibSp  Parch  Family  Family_Type
658  23.0       2      0      0       1            0
758  34.0       3      0      0       1            0
756  28.0       3      0      0       1            0
581  39.0       1      1      1       3            1
96   71.0       1      0      0       1            0
73   26.0       3      1      0       2            1
382  32.0       3      0      0       1            0
105  28.0       3      0      0       1            0
834  18.0       3      0      0       1            0
173  21.0       3      0      0       1            0
660  50.0       1      2      0       3            1
327  36.0       2      0      0       1            0

In [15]:
X.drop(columns=['SibSp','Parch','Family'],inplace=True)

In [16]:
np.mean(cross_val_score(LogisticRegression(),X,y,scoring="accuracy",cv=20))

np.float64(0.7003174603174602)

#Feature Splitting

In [17]:
df=pd.read_csv("/content/train.csv")

In [18]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [19]:
df['Name']

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

In [20]:
df['Title']=df['Name'].str.split(',',expand=True)[1].str.split('.',expand=True)[0]
df[['Title','Name']]

     Title                                               Name
0       Mr                            Braund, Mr. Owen Harris
1      Mrs  Cumings, Mrs. John Bradley (Florence Briggs Th...
2     Miss                             Heikkinen, Miss. Laina
3      Mrs       Futrelle, Mrs. Jacques Heath (Lily May Peel)
4       Mr                           Allen, Mr. William Henry
..     ...                                                ...
886    Rev                              Montvila, Rev. Juozas
887   Miss                       Graham, Miss. Margaret Edith
888   Miss           Johnston, Miss. Catherine Helen "Carrie"
889     Mr                              Behr, Mr. Karl Howell
890     Mr                                Dooley, Mr. Patrick

[891 rows x 2 columns]

In [21]:
df['Name'].str.split(',',expand=True)[1].str.split('.',expand=True)[0]

0         Mr
1        Mrs
2       Miss
3        Mrs
4         Mr
       ...
886      Rev
887     Miss
888     Miss
889       Mr
890       Mr
Name: 0, Length: 891, dtype: object

In [32]:
df['Title'].value_counts()

Title
Mr              517
Miss            182
Mrs             125
Master           40
Dr                7
Rev               6
Col               2
Mlle              2
Major             2
Ms                1
Mme               1
Don               1
Lady              1
Sir               1
Capt              1
the Countess      1
Jonkheer          1
Name: count, dtype: int64

In [44]:
df['Title'] = df['Title'].str.strip()

In [45]:
(df.groupby('Title')['Survived']).mean().sort_values(ascending=False)

Title
Lady            1.000000
Ms              1.000000
Sir             1.000000
Mme             1.000000
the Countess    1.000000
Mlle            1.000000
Mrs             0.792000
Miss            0.697802
Master          0.575000
Major           0.500000
Col             0.500000
Dr              0.428571
Mr              0.156673
Capt            0.000000
Jonkheer        0.000000
Don             0.000000
Rev             0.000000
Name: Survived, dtype: float64

In [49]:
df['Is_married']=0
df.loc[df['Title'] == 'Mrs', 'Is_married'] = 1

In [50]:
print(df['Title'].unique())

['Mr' 'Mrs' 'Miss' 'Master' 'Don' 'Rev' 'Dr' 'Mme' 'Ms' 'Major' 'Lady'
 'Sir' 'Mlle' 'Col' 'Capt' 'the Countess' 'Jonkheer']

In [51]:
df['Is_married']

0      0
1      1
2      0
3      1
4      0
      ..
886    0
887    0
888    0
889    0
890    0
Name: Is_married, Length: 891, dtype: int64